### PR TITLE
Add URL scheme for deep linking

### PR DESCRIPTION
**Pull request by alanjzhang**
I’d like to add Silas to [Air Launcher](https://apps.apple.com/ca/app/airlauncher-quick-launcher/id6477550630) without going through Shortcuts.

https://github.com/agg23/Sila/assets/12936379/7cd0c75f-10cb-4555-9e3c-47a7f67ebaff

### CODE REVIEW

**Comment by alanjzhang** [comment]
@agg23 FYI to get this building, I had to remove "Keys" from the build configuration to avoid this error: "Unable to open base configuration reference file '/Users/Alan/Sila/Keys.xcconfig'"

**Comment by agg23** [comment]
Thank you very much. This was something I intended to have from the beginning, but I forgot.

I would like to have proper routes set up for Following, Popular, Categories, and stream playback. I can do this work though.

> FYI to get this building, I had to remove "Keys" from the build configuration...

Thank you for pointing this out. I completely forgot to include instructions in the README on how to add the correct keys to the app. I'll do that soon.

**Comment by alanjzhang** [comment]
@agg23 Does this need anything else before merging?

**Comment by agg23** [comment]
I was preferring to wait until the feature is complete to merge it. Is there a reason for urgency?

**Comment by alanjzhang** [comment]
Ah no urgency, I selfishly wanted to use this to open Sila from [Air Launcher](https://apps.apple.com/ca/app/airlauncher-quick-launcher/id6477550630) (there are a few of these "dock" apps out there). Totally fine if you prefer to wait to set up routes first!

**Comment by agg23** [comment]
I understand that, but you have no guarantee that I was going to make a release right away. So you wouldn’t be able to use the change without building yourself anyway.

Hopefully I’ll get to it this weekend.

**Comment by agg23** [comment]
Support added in bead7bc1c4c1a67313c2f5cf1f02810adee482a9. Documentation has been added to the README

**Pull request merged**
